// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for GrammarCtypeConfidence.
const (
	High   GrammarCtypeConfidence = "high"
	Low    GrammarCtypeConfidence = "low"
	Medium GrammarCtypeConfidence = "medium"
)

// Valid indicates whether the value is a known member of the GrammarCtypeConfidence enum.
func (e GrammarCtypeConfidence) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for GrammarCtypeSource.
const (
	Existing   GrammarCtypeSource = "existing"
	Manual     GrammarCtypeSource = "manual"
	PosDerived GrammarCtypeSource = "pos-derived"
)

// Valid indicates whether the value is a known member of the GrammarCtypeSource enum.
func (e GrammarCtypeSource) Valid() bool {
	switch e {
	case Existing:
		return true
	case Manual:
		return true
	case PosDerived:
		return true
	default:
		return false
	}
}

// ApiInfo API トップページの基本情報
type ApiInfo struct {
	BuildDate   *string `json:"build_date,omitempty"`
	CommitShort *string `json:"commit_short,omitempty"`
	Description string  `json:"description"`

	// Docs API ドキュメント（Redoc）の URL
	Docs string `json:"docs"`

	// Endpoints 主要エンドポイント一覧
	Endpoints []EndpointInfo `json:"endpoints"`

	// EntryCount 収録語彙数
	EntryCount *string `json:"entry_count,omitempty"`

	// Frontend 利用者向け前端サイト
	Frontend string `json:"frontend"`
	Name     string `json:"name"`

	// Openapi OpenAPI 仕様の URL
	Openapi string `json:"openapi"`

	// Version 辞書データのバージョン（_metadata 由来）
	Version *string `json:"version,omitempty"`
}

// Citation defines model for Citation.
type Citation struct {
	Author *string `json:"author,omitempty"`
	Note   *string `json:"note,omitempty"`
	Source *string `json:"source,omitempty"`
}

// Definition defines model for Definition.
type Definition struct {
	Collocations *[]string    `json:"collocations,omitempty"`
	Examples     *Examples    `json:"examples,omitempty"`
	Gloss        *string      `json:"gloss,omitempty"`
	Index        *int         `json:"index,omitempty"`
	Nuance       *string      `json:"nuance,omitempty"`
	Register     *string      `json:"register,omitempty"`
	Scenarios    *[]string    `json:"scenarios,omitempty"`
	SensoryTags  *SensoryTags `json:"sensory_tags,omitempty"`
}

// DefinitionSearchResult defines model for DefinitionSearchResult.
type DefinitionSearchResult struct {
	DefIndex *int    `json:"def_index,omitempty"`
	Entry    string  `json:"entry"`
	Gloss    *string `json:"gloss,omitempty"`

	// MatchHighlight マッチ箇所のハイライト（<b> タグ付き）
	MatchHighlight *string `json:"match_highlight,omitempty"`
	ReadingPrimary *string `json:"reading_primary,omitempty"`
	Uuid           string  `json:"uuid"`
}

// DefinitionSearchResultList defines model for DefinitionSearchResultList.
type DefinitionSearchResultList struct {
	Count   int                      `json:"count"`
	Query   *string                  `json:"query,omitempty"`
	Results []DefinitionSearchResult `json:"results"`
}

// EndpointInfo defines model for EndpointInfo.
type EndpointInfo struct {
	Path    string `json:"path"`
	Summary string `json:"summary"`
}

// Entry defines model for Entry.
type Entry struct {
	Definitions *[]Definition `json:"definitions,omitempty"`
	Entry       string        `json:"entry"`
	Grammar     *Grammar      `json:"grammar,omitempty"`
	Meta        *EntryMeta    `json:"meta,omitempty"`
	Reading     *Reading      `json:"reading,omitempty"`
	Relations   *Relations    `json:"relations,omitempty"`
	Uuid        string        `json:"uuid"`
}

// EntryList defines model for EntryList.
type EntryList struct {
	Count   int     `json:"count"`
	Entries []Entry `json:"entries"`
}

// EntryMeta defines model for EntryMeta.
type EntryMeta struct {
	// FreqRank 頻度ランク（小さいほど高頻度。hingston/japanese 由来）
	FreqRank *int `json:"freq_rank,omitempty"`

	// Frequencies 出典別の総出現回数。例: {"aozora": 1234}
	Frequencies *map[string]int `json:"frequencies,omitempty"`
	Source      *string         `json:"source,omitempty"`
	UpdatedAt   *string         `json:"updated_at,omitempty"`
	Version     *string         `json:"version,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Example defines model for Example.
type Example struct {
	Citation *Citation `json:"citation,omitempty"`
	Text     *string   `json:"text,omitempty"`
}

// Examples defines model for Examples.
type Examples struct {
	Literary *[]Example `json:"literary,omitempty"`
	Standard *[]Example `json:"standard,omitempty"`
}

// Grammar defines model for Grammar.
type Grammar struct {
	Ctype *string `json:"ctype,omitempty"`

	// CtypeConfidence 活用型の信頼度。
	CtypeConfidence *GrammarCtypeConfidence `json:"ctype_confidence,omitempty"`

	// CtypeSource 活用型の由来。既存値、POS からの推導、または人工指定。
	CtypeSource *GrammarCtypeSource `json:"ctype_source,omitempty"`

	// Inflections 活用情報（任意の JSON）
	Inflections interface{} `json:"inflections,omitempty"`
	Pos         *[]string   `json:"pos,omitempty"`
}

// GrammarCtypeConfidence 活用型の信頼度。
type GrammarCtypeConfidence string

// GrammarCtypeSource 活用型の由来。既存値、POS からの推導、または人工指定。
type GrammarCtypeSource string

// Health defines model for Health.
type Health struct {
	// Cache キャッシュの状態（enabled / disabled）
	Cache  *string `json:"cache,omitempty"`
	Status string  `json:"status"`
}

// Metadata _metadata テーブルの内容
type Metadata struct {
	Branch        *string `json:"branch,omitempty"`
	BuildDate     *string `json:"build_date,omitempty"`
	Commit        *string `json:"commit,omitempty"`
	CommitShort   *string `json:"commit_short,omitempty"`
	EntryCount    *string `json:"entry_count,omitempty"`
	Repository    *string `json:"repository,omitempty"`
	SchemaVersion *string `json:"schema_version,omitempty"`
	Version       *string `json:"version,omitempty"`
}

// Reading defines model for Reading.
type Reading struct {
	Alternatives *[]string `json:"alternatives,omitempty"`
	IsHeteronym  *bool     `json:"is_heteronym,omitempty"`
	Primary      *string   `json:"primary,omitempty"`
}

// Relations defines model for Relations.
type Relations struct {
	Antonyms   *[]string `json:"antonyms,omitempty"`
	Homophones *[]string `json:"homophones,omitempty"`
	Related    *[]string `json:"related,omitempty"`
	Synonyms   *[]string `json:"synonyms,omitempty"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Entry string `json:"entry"`

	// MatchHighlight マッチ箇所のハイライト（<b> タグ付き）
	MatchHighlight *string   `json:"match_highlight,omitempty"`
	Pos            *[]string `json:"pos,omitempty"`
	ReadingPrimary *string   `json:"reading_primary,omitempty"`
	Uuid           string    `json:"uuid"`
}

// SearchResultList defines model for SearchResultList.
type SearchResultList struct {
	Count   int            `json:"count"`
	Query   *string        `json:"query,omitempty"`
	Results []SearchResult `json:"results"`
}

// SensoryTags defines model for SensoryTags.
type SensoryTags struct {
	Colors      *[]string `json:"colors,omitempty"`
	Emotions    *[]string `json:"emotions,omitempty"`
	Sounds      *[]string `json:"sounds,omitempty"`
	Temperature *string   `json:"temperature,omitempty"`
}

// SitemapItem defines model for SitemapItem.
type SitemapItem struct {
	Entry string `json:"entry"`

	// Heat 熱度指数（2×直近30日 + 1×直近365日のアクセス数）。Redis 無効時は null
	Heat           *float64 `json:"heat,omitempty"`
	ReadingPrimary *string  `json:"reading_primary,omitempty"`

	// UpdatedAt エントリの更新日時（sitemap の lastmod 用）
	UpdatedAt *string `json:"updated_at,omitempty"`
	Uuid      string  `json:"uuid"`
}

// SitemapPage defines model for SitemapPage.
type SitemapPage struct {
	Items    []SitemapItem `json:"items"`
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`

	// Total 全収録語彙数
	Total      int `json:"total"`
	TotalPages int `json:"total_pages"`
}

// LookupByEntryParams defines parameters for LookupByEntry.
type LookupByEntryParams struct {
	// Word 見出し語（漢字・カタカナ等）
	Word string `form:"word" json:"word"`
}

// LookupByReadingParams defines parameters for LookupByReading.
type LookupByReadingParams struct {
	// Reading 読み（ひらがな・カタカナ）
	Reading string `form:"reading" json:"reading"`
}

// RandomEntriesParams defines parameters for RandomEntries.
type RandomEntriesParams struct {
	// Count 取得件数
	Count *int `form:"count,omitempty" json:"count,omitempty"`
}

// SearchDefinitionsParams defines parameters for SearchDefinitions.
type SearchDefinitionsParams struct {
	// Q 検索クエリ（英語の語釈にマッチ）
	Q string `form:"q" json:"q"`

	// Limit 取得件数の上限
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// SearchEntriesParams defines parameters for SearchEntries.
type SearchEntriesParams struct {
	// Q 検索クエリ
	Q string `form:"q" json:"q"`

	// Limit 取得件数の上限
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSitemapParams defines parameters for GetSitemap.
type GetSitemapParams struct {
	// Page ページ番号（1 始まり）
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize 1 ページあたりの件数
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// API トップ情報
	// (GET /)
	GetApiInfo(c *gin.Context)
	// ヘルスチェック
	// (GET /healthz)
	GetHealth(c *gin.Context)
	// UUID でエントリ取得
	// (GET /v1/entries/{uuid})
	GetEntryByUUID(c *gin.Context, uuid string)
	// 見出し語で検索（完全一致）
	// (GET /v1/lookup/entry)
	LookupByEntry(c *gin.Context, params LookupByEntryParams)
	// 読みで検索（完全一致）
	// (GET /v1/lookup/reading)
	LookupByReading(c *gin.Context, params LookupByReadingParams)
	// ビルドメタデータ取得
	// (GET /v1/metadata)
	GetMetadata(c *gin.Context)
	// ランダムな語を取得
	// (GET /v1/random)
	RandomEntries(c *gin.Context, params RandomEntriesParams)
	// 語釈を全文検索
	// (GET /v1/search/definitions)
	SearchDefinitions(c *gin.Context, params SearchDefinitionsParams)
	// 見出し語・読みを全文検索
	// (GET /v1/search/entries)
	SearchEntries(c *gin.Context, params SearchEntriesParams)
	// 対象品詞の語彙を熱度順にページングして取得
	// (GET /v1/sitemap)
	GetSitemap(c *gin.Context, params GetSitemapParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetApiInfo operation middleware
func (siw *ServerInterfaceWrapper) GetApiInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiInfo(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetEntryByUUID operation middleware
func (siw *ServerInterfaceWrapper) GetEntryByUUID(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "uuid" -------------
	var uuid string

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", c.Param("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter uuid: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetEntryByUUID(c, uuid)
}

// LookupByEntry operation middleware
func (siw *ServerInterfaceWrapper) LookupByEntry(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LookupByEntryParams

	// ------------- Required query parameter "word" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "word", c.Request.URL.Query(), &params.Word, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter word: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LookupByEntry(c, params)
}

// LookupByReading operation middleware
func (siw *ServerInterfaceWrapper) LookupByReading(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params LookupByReadingParams

	// ------------- Required query parameter "reading" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "reading", c.Request.URL.Query(), &params.Reading, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter reading: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LookupByReading(c, params)
}

// GetMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetMetadata(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMetadata(c)
}

// RandomEntries operation middleware
func (siw *ServerInterfaceWrapper) RandomEntries(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RandomEntriesParams

	// ------------- Optional query parameter "count" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "count", c.Request.URL.Query(), &params.Count, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter count: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RandomEntries(c, params)
}

// SearchDefinitions operation middleware
func (siw *ServerInterfaceWrapper) SearchDefinitions(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchDefinitionsParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", c.Request.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchDefinitions(c, params)
}

// SearchEntries operation middleware
func (siw *ServerInterfaceWrapper) SearchEntries(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchEntriesParams

	// ------------- Required query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "q", c.Request.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchEntries(c, params)
}

// GetSitemap operation middleware
func (siw *ServerInterfaceWrapper) GetSitemap(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSitemapParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", c.Request.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSitemap(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/", wrapper.GetApiInfo)
	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
	router.GET(options.BaseURL+"/v1/entries/:uuid", wrapper.GetEntryByUUID)
	router.GET(options.BaseURL+"/v1/lookup/entry", wrapper.LookupByEntry)
	router.GET(options.BaseURL+"/v1/lookup/reading", wrapper.LookupByReading)
	router.GET(options.BaseURL+"/v1/metadata", wrapper.GetMetadata)
	router.GET(options.BaseURL+"/v1/random", wrapper.RandomEntries)
	router.GET(options.BaseURL+"/v1/search/definitions", wrapper.SearchDefinitions)
	router.GET(options.BaseURL+"/v1/search/entries", wrapper.SearchEntries)
	router.GET(options.BaseURL+"/v1/sitemap", wrapper.GetSitemap)
}

type GetApiInfoRequestObject struct {
}

type GetApiInfoResponseObject interface {
	VisitGetApiInfoResponse(w http.ResponseWriter) error
}

type GetApiInfo200JSONResponse ApiInfo

func (response GetApiInfo200JSONResponse) VisitGetApiInfoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse Error

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetEntryByUUIDRequestObject struct {
	Uuid string `json:"uuid"`
}

type GetEntryByUUIDResponseObject interface {
	VisitGetEntryByUUIDResponse(w http.ResponseWriter) error
}

type GetEntryByUUID200JSONResponse Entry

func (response GetEntryByUUID200JSONResponse) VisitGetEntryByUUIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetEntryByUUID404JSONResponse Error

func (response GetEntryByUUID404JSONResponse) VisitGetEntryByUUIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type LookupByEntryRequestObject struct {
	Params LookupByEntryParams
}

type LookupByEntryResponseObject interface {
	VisitLookupByEntryResponse(w http.ResponseWriter) error
}

type LookupByEntry200JSONResponse EntryList

func (response LookupByEntry200JSONResponse) VisitLookupByEntryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type LookupByReadingRequestObject struct {
	Params LookupByReadingParams
}

type LookupByReadingResponseObject interface {
	VisitLookupByReadingResponse(w http.ResponseWriter) error
}

type LookupByReading200JSONResponse EntryList

func (response LookupByReading200JSONResponse) VisitLookupByReadingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMetadataRequestObject struct {
}

type GetMetadataResponseObject interface {
	VisitGetMetadataResponse(w http.ResponseWriter) error
}

type GetMetadata200JSONResponse Metadata

func (response GetMetadata200JSONResponse) VisitGetMetadataResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RandomEntriesRequestObject struct {
	Params RandomEntriesParams
}

type RandomEntriesResponseObject interface {
	VisitRandomEntriesResponse(w http.ResponseWriter) error
}

type RandomEntries200JSONResponse EntryList

func (response RandomEntries200JSONResponse) VisitRandomEntriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchDefinitionsRequestObject struct {
	Params SearchDefinitionsParams
}

type SearchDefinitionsResponseObject interface {
	VisitSearchDefinitionsResponse(w http.ResponseWriter) error
}

type SearchDefinitions200JSONResponse DefinitionSearchResultList

func (response SearchDefinitions200JSONResponse) VisitSearchDefinitionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchEntriesRequestObject struct {
	Params SearchEntriesParams
}

type SearchEntriesResponseObject interface {
	VisitSearchEntriesResponse(w http.ResponseWriter) error
}

type SearchEntries200JSONResponse SearchResultList

func (response SearchEntries200JSONResponse) VisitSearchEntriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSitemapRequestObject struct {
	Params GetSitemapParams
}

type GetSitemapResponseObject interface {
	VisitGetSitemapResponse(w http.ResponseWriter) error
}

type GetSitemap200JSONResponse SitemapPage

func (response GetSitemap200JSONResponse) VisitGetSitemapResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// API トップ情報
	// (GET /)
	GetApiInfo(ctx context.Context, request GetApiInfoRequestObject) (GetApiInfoResponseObject, error)
	// ヘルスチェック
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// UUID でエントリ取得
	// (GET /v1/entries/{uuid})
	GetEntryByUUID(ctx context.Context, request GetEntryByUUIDRequestObject) (GetEntryByUUIDResponseObject, error)
	// 見出し語で検索（完全一致）
	// (GET /v1/lookup/entry)
	LookupByEntry(ctx context.Context, request LookupByEntryRequestObject) (LookupByEntryResponseObject, error)
	// 読みで検索（完全一致）
	// (GET /v1/lookup/reading)
	LookupByReading(ctx context.Context, request LookupByReadingRequestObject) (LookupByReadingResponseObject, error)
	// ビルドメタデータ取得
	// (GET /v1/metadata)
	GetMetadata(ctx context.Context, request GetMetadataRequestObject) (GetMetadataResponseObject, error)
	// ランダムな語を取得
	// (GET /v1/random)
	RandomEntries(ctx context.Context, request RandomEntriesRequestObject) (RandomEntriesResponseObject, error)
	// 語釈を全文検索
	// (GET /v1/search/definitions)
	SearchDefinitions(ctx context.Context, request SearchDefinitionsRequestObject) (SearchDefinitionsResponseObject, error)
	// 見出し語・読みを全文検索
	// (GET /v1/search/entries)
	SearchEntries(ctx context.Context, request SearchEntriesRequestObject) (SearchEntriesResponseObject, error)
	// 対象品詞の語彙を熱度順にページングして取得
	// (GET /v1/sitemap)
	GetSitemap(ctx context.Context, request GetSitemapRequestObject) (GetSitemapResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetApiInfo operation middleware
func (sh *strictHandler) GetApiInfo(ctx *gin.Context) {
	var request GetApiInfoRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiInfo(ctx, request.(GetApiInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiInfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetApiInfoResponseObject); ok {
		if err := validResponse.VisitGetApiInfoResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx *gin.Context) {
	var request GetHealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEntryByUUID operation middleware
func (sh *strictHandler) GetEntryByUUID(ctx *gin.Context, uuid string) {
	var request GetEntryByUUIDRequestObject

	request.Uuid = uuid

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetEntryByUUID(ctx, request.(GetEntryByUUIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEntryByUUID")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetEntryByUUIDResponseObject); ok {
		if err := validResponse.VisitGetEntryByUUIDResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LookupByEntry operation middleware
func (sh *strictHandler) LookupByEntry(ctx *gin.Context, params LookupByEntryParams) {
	var request LookupByEntryRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LookupByEntry(ctx, request.(LookupByEntryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LookupByEntry")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LookupByEntryResponseObject); ok {
		if err := validResponse.VisitLookupByEntryResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// LookupByReading operation middleware
func (sh *strictHandler) LookupByReading(ctx *gin.Context, params LookupByReadingParams) {
	var request LookupByReadingRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LookupByReading(ctx, request.(LookupByReadingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LookupByReading")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LookupByReadingResponseObject); ok {
		if err := validResponse.VisitLookupByReadingResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetadata operation middleware
func (sh *strictHandler) GetMetadata(ctx *gin.Context) {
	var request GetMetadataRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetadata(ctx, request.(GetMetadataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetadata")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetMetadataResponseObject); ok {
		if err := validResponse.VisitGetMetadataResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RandomEntries operation middleware
func (sh *strictHandler) RandomEntries(ctx *gin.Context, params RandomEntriesParams) {
	var request RandomEntriesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RandomEntries(ctx, request.(RandomEntriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RandomEntries")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RandomEntriesResponseObject); ok {
		if err := validResponse.VisitRandomEntriesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchDefinitions operation middleware
func (sh *strictHandler) SearchDefinitions(ctx *gin.Context, params SearchDefinitionsParams) {
	var request SearchDefinitionsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchDefinitions(ctx, request.(SearchDefinitionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchDefinitions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(SearchDefinitionsResponseObject); ok {
		if err := validResponse.VisitSearchDefinitionsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchEntries operation middleware
func (sh *strictHandler) SearchEntries(ctx *gin.Context, params SearchEntriesParams) {
	var request SearchEntriesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchEntries(ctx, request.(SearchEntriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchEntries")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(SearchEntriesResponseObject); ok {
		if err := validResponse.VisitSearchEntriesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSitemap operation middleware
func (sh *strictHandler) GetSitemap(ctx *gin.Context, params GetSitemapParams) {
	var request GetSitemapRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSitemap(ctx, request.(GetSitemapRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSitemap")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetSitemapResponseObject); ok {
		if err := validResponse.VisitGetSitemapResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
